# Generated by Django 3.0.8 on 2020-07-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0002_auto_20200722_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='realease_date',
            new_name='release_date',
        ),
    ]
